import React, { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { audioPlayer, audioTracks, type AudioTrack } from "@/lib/audio";

interface MusicTrackProps {
  track: AudioTrack;
  isPlaying: boolean;
  onPlayPause: (id: number) => void;
}

const MusicTrack: React.FC<MusicTrackProps> = ({ track, isPlaying, onPlayPause }) => {
  return (
    <motion.div 
      className="bg-[#1E1E1E] rounded-xl overflow-hidden border border-[#2979FF]/20 shadow-lg p-6"
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ duration: 0.5 }}
    >
      <div className="flex items-center justify-between mb-4">
        <div>
          <h3 className="text-xl font-orbitron font-bold text-white">{track.title}</h3>
          <p className="text-gray-400">{track.series}</p>
        </div>
        <div className="flex gap-3">
          <button 
            className="audio-control play-button" 
            onClick={() => onPlayPause(track.id)}
            aria-label={isPlaying ? "Pause" : "Play"}
          >
            <i className={`fas ${isPlaying ? 'fa-pause' : 'fa-play'}`}></i>
          </button>
          <a href="#" className="audio-control" aria-label="Spotify">
            <i className="fab fa-spotify"></i>
          </a>
        </div>
      </div>
      
      <div className="waveform mb-4">
        <div 
          className="absolute inset-0 bg-gradient-to-r from-[#2979FF] via-[#08FDD8] to-[#4A148C] opacity-70"
          style={{
            maskImage: "url('data:image/svg+xml;utf8,<svg viewBox=\"0 0 1200 60\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M0,30 Q60,5 120,30 T240,30 T360,30 T480,30 T600,30 T720,30 T840,30 T960,30 T1080,30 T1200,30\" fill=\"none\" stroke=\"white\" stroke-width=\"2\" /></svg>')",
            maskSize: "300% 100%",
            animation: isPlaying ? "wave 10s linear infinite" : "none"
          }}
        />
      </div>
      
      <div className="flex items-center justify-between text-sm">
        <span className="text-gray-400">Generated by <span className="text-[#FF2E63]">{track.producer}</span></span>
        <div className="flex items-center gap-4">
          <span className="text-gray-400">{track.duration}</span>
          <span className="text-gray-400">{track.bpm}</span>
        </div>
      </div>
    </motion.div>
  );
};

const MusicLabSection: React.FC = () => {
  const [playingTrackId, setPlayingTrackId] = useState<number | null>(null);

  // Handle play/pause
  const handlePlayPause = (trackId: number) => {
    audioPlayer.play(trackId);
    setPlayingTrackId(audioPlayer.getCurrentTrackId());
  };

  // Sync with the audio player's state
  useEffect(() => {
    const checkAudioState = setInterval(() => {
      setPlayingTrackId(audioPlayer.getCurrentTrackId());
    }, 500);

    return () => clearInterval(checkAudioState);
  }, []);

  return (
    <section id="music" className="py-20 bg-gradient-dark relative overflow-hidden">
      <div className="shape-blob bg-[#FF2E63]/10 w-96 h-96 -bottom-48 right-20 animate-float" style={{ animationDelay: "2s" }}></div>
      
      <div className="container mx-auto px-4 md:px-6">
        <motion.div 
          className="text-center mb-16"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
        >
          <h2 className="text-3xl md:text-4xl font-orbitron font-bold mb-6">
            Patang <span className="text-gradient">Music Lab</span>
          </h2>
          <p className="max-w-2xl mx-auto text-lg text-gray-300">
            AI-generated trance music with emotion-mapping, beatsync, and voice layering technology
          </p>
        </motion.div>
        
        {/* Music tracks grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-16">
          {audioTracks.map((track) => (
            <MusicTrack 
              key={track.id}
              track={track}
              isPlaying={playingTrackId === track.id}
              onPlayPause={handlePlayPause}
            />
          ))}
        </div>
        
        {/* Music Lab Info */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
          <motion.div
            initial={{ opacity: 0, x: -30 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.7 }}
          >
            <img 
              src="https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&h=800" 
              alt="Futuristic AI music studio with digital equipment" 
              className="rounded-xl shadow-lg shadow-[#2979FF]/20 w-full h-auto"
            />
          </motion.div>
          
          <div className="space-y-6">
            <motion.h3 
              className="text-2xl font-orbitron font-bold"
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5 }}
            >
              How Our AI Creates Music
            </motion.h3>
            
            <div className="space-y-6">
              {/* Feature 1 */}
              <motion.div 
                className="flex gap-4"
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: 0.1 }}
              >
                <div className="flex-shrink-0 w-12 h-12 bg-[#2979FF]/20 rounded-lg flex items-center justify-center text-[#2979FF]">
                  <i className="fas fa-brain text-xl"></i>
                </div>
                <div>
                  <h4 className="text-lg font-orbitron text-white mb-2">Emotion Mapping</h4>
                  <p className="text-gray-300">Our AI analyzes emotional states and translates them into musical patterns, harmonies, and progressions that evoke specific feelings.</p>
                </div>
              </motion.div>
              
              {/* Feature 2 */}
              <motion.div 
                className="flex gap-4"
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: 0.2 }}
              >
                <div className="flex-shrink-0 w-12 h-12 bg-[#FF2E63]/20 rounded-lg flex items-center justify-center text-[#FF2E63]">
                  <i className="fas fa-wave-square text-xl"></i>
                </div>
                <div>
                  <h4 className="text-lg font-orbitron text-white mb-2">BeatSync Technology</h4>
                  <p className="text-gray-300">Proprietary algorithms create perfectly synchronized beats, basslines, and melodic elements that evolve organically throughout the track.</p>
                </div>
              </motion.div>
              
              {/* Feature 3 */}
              <motion.div 
                className="flex gap-4"
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: 0.3 }}
              >
                <div className="flex-shrink-0 w-12 h-12 bg-[#08FDD8]/20 rounded-lg flex items-center justify-center text-[#08FDD8]">
                  <i className="fas fa-microphone-alt text-xl"></i>
                </div>
                <div>
                  <h4 className="text-lg font-orbitron text-white mb-2">Voice Layering</h4>
                  <p className="text-gray-300">Synthetic vocals generated by our AI models add human-like elements while maintaining the otherworldly quality that defines our sound.</p>
                </div>
              </motion.div>
            </div>
            
            <motion.div 
              className="flex flex-wrap gap-4 pt-4"
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: 0.4 }}
            >
              <a 
                href="#" 
                className="px-6 py-3 bg-[#FF2E63] hover:bg-[#FF2E63]/80 text-white font-orbitron rounded-md transition-all duration-300"
              >
                Explore Full Catalog
              </a>
              <a 
                href="#" 
                className="px-6 py-3 flex items-center gap-2 bg-transparent border border-white/20 text-white hover:bg-white/5 font-orbitron rounded-md transition-all duration-300"
              >
                <i className="fab fa-soundcloud"></i> SoundCloud
              </a>
            </motion.div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default MusicLabSection;
